name: qt-framework-sdk
base: core22
version: 6.5.2
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: devel
confinement: strict

parts:
  mesa:
    after: []
    plugin: nil
    build-attributes:
    - no-patchelf
    build-packages: []
    stage-packages:
    - libgl1-mesa-dri
    - libglx-mesa0
    prime:
    - -lib/udev
    - -usr/doc
    - -usr/doc-base
    - -usr/share/applications
    - -usr/share/apport
    - -usr/share/bug
    - -usr/share/doc
    - -usr/share/doc-base
    - -usr/share/icons
    - -usr/share/libdrm
    - -usr/share/libwacom
    - -usr/share/lintian
    - -usr/share/man
    - -usr/share/pkgconfig
  build-deps:
    plugin: nil
    build-packages:
      # ALL
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
      # 6.4
      - clang
      - libmd4c-dev
      - libmd4c-html0-dev
      - llvm-dev
  qt6-5:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.5.2
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/$CRAFT_PART_NAME
  qt6-4:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.4.3
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/$CRAFT_PART_NAME
