name: qt-framework-sdk
base: core22
version: 6.5.2
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

parts:
  qt6:
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
      - libfontconfig1-dev
      - libfreetype6-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxext-dev
      - libxfixes-dev
      - libxi-dev
      - libxrender-dev
      - libxcb1-dev
      - libxcb-glx0-dev
      - libxcb-keysyms1-dev
      - libxcb-image0-dev
      - libxcb-shm0-dev
      - libxcb-icccm4-dev
      - libxcb-sync0-dev
      - libxcb-xfixes0-dev
      - libxcb-shape0-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-xinerama0-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libwayland-dev
      - libwayland-egl1-mesa
      - libwayland-server0
      - libgles2-mesa-dev
      - libxkbcommon-dev
      - gperf
      - clang
      - bison
      - flex
      - nodejs
      - python2-minimal
      - python-pip
      - libnss3-dev
      - libdbus-1-dev
      - libdrm-dev
      - libxcomposite-dev
      - libxcursor-dev
      - libxtst-dev
      - llvm-dev
    organize:
      usr/lib: usr/lib/$CRAFT_ARCH_TRIPLET
      usr/libexec: usr/lib/$CRAFT_ARCH_TRIPLET/qt6/libexec
      usr/bin: usr/lib/$CRAFT_ARCH_TRIPLET/qt6/bin
      usr/include: usr/include/$CRAFT_ARCH_TRIPLET/qt6
      usr/plugins: usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
      usr/qml: usr/lib/$CRAFT_ARCH_TRIPLET/qt6/qml
      usr/translations: usr/share/qt6/translations
      usr/phrasebooks: usr/share/qt6/phrasebooks
      usr/metatypes: usr/lib/$CRAFT_ARCH_TRIPLET/metatypes
      usr/mkspecs: usr/lib/$CRAFT_ARCH_TRIPLET/qt6/mkspecs
      usr/modules: usr/share/qt6/modules
      usr/doc: usr/share/qt6/doc
