name: qt-framework-sdk
base: core22
version: bundle
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

parts:
  mesa:
    after: []
    plugin: nil
    build-attributes:
    - no-patchelf
    build-packages: []
    stage-packages:
    - libgl1-mesa-dri
    - libglx-mesa0
    prime:
    - -lib/udev
    - -usr/doc
    - -usr/doc-base
    - -usr/share/applications
    - -usr/share/apport
    - -usr/share/bug
    - -usr/share/doc
    - -usr/share/doc-base
    - -usr/share/icons
    - -usr/share/libdrm
    - -usr/share/libwacom
    - -usr/share/lintian
    - -usr/share/man
    - -usr/share/pkgconfig
  build-deps:
    plugin: nil
    build-packages:
      # ALL
      - python3-minimal
      - libclang-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - ninja-build
      # 6.4
      - clang
      - libmd4c-dev
      - libmd4c-html0-dev
      - llvm-dev
  qt6-5:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.5.2
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/$CRAFT_PART_NAME
  qt6-4:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.4.3
    source-submodules:
      - qt3d
      - qt5compat
      - qt6-build
      - qtactiveqt
      - qtbase
      - qtcanvas3d
      - qtcharts
      - qtcoap
      - qtconnectivity
      - qtdatavis3d
      - qtdeclarative
      - qtdoc
      - qtfeedback
      - qtgamepad
      - qthttpserver
      - qtimageformats
      - qtlanguageserver
      # - qtlocation
      - qtlottie
      - qtmqtt
      - qtmultimedia
      - qtnetworkauth
      - qtopcua
      - qtpim
      - qtpositioning
      - qtqa
      - qtquick3d
      - qtquick3dphysics
      - qtquicktimeline
      - qtremoteobjects
      - qtrepotools
      - qtscxml
      - qtsensors
      - qtserialbus
      - qtserialport
      - qtshadertools
      - qtspeech
      - qtsvg
      - qtsystems
      - qttools
      - qttranslations
      - qtvirtualkeyboard
      - qtwayland
      - qtwebchannel
      - qtwebengine
      - qtwebglplugin
      - qtwebsockets
      - qtwebview
      - qtxmlpatterns
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/$CRAFT_PART_NAME
  qt6-2:
    after: [build-deps, mesa]
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v6.2.4
    source-submodules:
      - qt3d
      - qt5compat
      - qt6-build
      - qtactiveqt
      - qtbase
      - qtcanvas3d
      - qtcharts
      - qtcoap
      - qtconnectivity
      - qtdatavis3d
      - qtdeclarative
      - qtdoc
      - qtfeedback
      - qtgamepad
      - qthttpserver
      - qtimageformats
      - qtlanguageserver
      # - qtlocation
      - qtlottie
      - qtmqtt
      - qtmultimedia
      - qtnetworkauth
      - qtopcua
      - qtpim
      - qtpositioning
      - qtqa
      - qtquick3d
      - qtquick3dphysics
      - qtquicktimeline
      - qtremoteobjects
      - qtrepotools
      - qtscxml
      - qtsensors
      - qtserialbus
      - qtserialport
      - qtshadertools
      - qtspeech
      - qtsvg
      - qtsystems
      - qttools
      - qttranslations
      - qtvirtualkeyboard
      - qtwayland
      - qtwebchannel
      - qtwebengine
      - qtwebglplugin
      - qtwebsockets
      - qtwebview
      - qtxmlpatterns
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/opt/$CRAFT_PART_NAME
