name: qt-framework-sdk
base: core22
version: 6.6.0-rc1
summary: Qt Framework SDK
description: |
  Qt is a cross-platform application development framework widely used
  for developing software with graphical user interfaces (GUIs) and
  interactive functionality.

grade: stable
confinement: strict

package-repositories:
  - type: apt
    url: https://deb.nodesource.com/node_20.x
    components: [main]
    suites: [nodistro]
    key-id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4

parts:
  qt6:
    plugin: cmake
    source: https://code.qt.io/qt/qt5.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_LIBRARY_PATH=$CRAFT_ARCH_TRIPLET
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DINSTALL_BINDIR=lib/qt6/bin
      - -DINSTALL_LIBDIR=lib/$CRAFT_ARCH_TRIPLET
      - -DINSTALL_LIBEXECDIR=lib/qt6/libexec
      - -DINSTALL_ARCHDATADIR=lib/$CRAFT_ARCH_TRIPLET/qt6
      - -DINSTALL_EXAMPLESDIR=lib/$CRAFT_ARCH_TRIPLET/qt6/examples
      - -DINSTALL_DATADIR=share/qt6
      - -DINSTALL_HOSTDATADIR=lib/$CRAFT_ARCH_TRIPLET/qt6
      - -DINSTALL_DOCDIR=share/qt6/doc
      - -DINSTALL_SYSCONFDIR=/etc/xdg
      - -DINSTALL_INCLUDEDIR=include/$CRAFT_ARCH_TRIPLET/qt6
      - -DINSTALL_PLUGINDIR=lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
      - -DINSTALL_TRANSLATIONDIR=share/qt6/translations
      - -DINSTALL_MKSPECSDIR=lib/$CRAFT_ARCH_TRIPLET/qt6/mkspecs
      - -DINSTALL_PUBLICBINDIR=bin
      - -DBUILD_EXAMPLES=ON
      - -DFEATURE_mimetype_database=OFF
      - -DFEATURE_dbus_linked=ON
      - -DFEATURE_accessibility=ON
      - -DFEATURE_doubleconversion=ON
      - -DFEATURE_glib=ON
      - -DFEATURE_icu=ON
      - -DFEATURE_pcre2=ON
      - -DFEATURE_system_pcre2=ON
      - -DFEATURE_zlib=ON
      - -DFEATURE_ssl=ON
      - -DFEATURE_libproxy=ON
      - -DFEATURE_system_proxies=ON
      - -DFEATURE_cups=ON
      - -DFEATURE_fontconfig=ON
      - -DFEATURE_freetype=ON
      - -DFEATURE_harfbuzz=ON
      - -DFEATURE_gtk=ON
      - -DFEATURE_directfb=OFF
      - -DFEATURE_sql_odbc=ON
      - -DFEATURE_sql_mysql=ON
      - -DFEATURE_sql_psql=ON
      - -DFEATURE_sql_sqlite=ON
      - -DFEATURE_system_sqlite=ON
      - -DFEATURE_jpeg=ON
      - -DFEATURE_system_jpeg=ON
      - -DFEATURE_png=ON
      - -DFEATURE_system_png=ON
      - -DFEATURE_system_libb2=ON
      - -DFEATURE_rpath=OFF
      - -DFEATURE_relocatable=OFF
      - -DFEATURE_qtpdf_build=ON
      - -DFEATURE_qtpdf_enable_v8=ON
      - -DFEATURE_qtpdf_quick_build=ON
      - -DFEATURE_qtpdf_widgets_build=ON
      - -DFEATURE_qtwebengine-quick-build=ON
      - -DFEATURE_qtwebengine-widgets-build=ON
      - -DFEATURE_webengine_kerberos=ON
      - -DFEATURE_webengine_proprietary_codecs=ON
      - -DFEATURE_webengine_system_icu=OFF
      # - -DFEATURE_webengine_system_libevent=ON
      - -DFEATURE_webengine-system-libjpeg=on
      - -DFEATURE_webengine-system-libpng=on
      - -DFEATURE_webengine_system_zlib=ON
      - -DFEATURE_webengine_webrtc=ON
      - -DFEATURE_webengine_webrtc-pipewire=ON
      - -DQT_FEATURE_alsa=ON
    build-packages:
      - libpq-dev
      - libxcb-glx0-dev
      - libjpeg-dev
      - libdrm-dev
      - libxcb-render-util0-dev
      - libxcursor-dev
      - zlib1g-dev
      - liblttng-ust-dev
      - libxkbcommon-x11-dev
      - libxcomposite-dev
      - libatspi2.0-dev
      - libxcb-xtest0-dev
      - firebird-dev
      - libwayland-server0
      - libxrender-dev
      - libxcb-record0-dev
      - libgl1-mesa-dev
      - python3-minimal
      - libglib2.0-dev
      - python2-minimal
      - libxcb-xvmc0-dev
      - libxcb-xv0-dev
      - libx11-dev
      - libfontconfig-dev
      - libxkbcommon-dev
      - libxcb-dri2-0-dev
      - libicu-dev
      - gperf
      - libgl-dev
      - libdouble-conversion-dev
      - libglu-dev
      - libgles2-mesa-dev
      - python-pip
      - llvm-dev
      - libzstd-dev
      - unixodbc-dev
      - libsystemd-dev
      - libxcb-xrm-dev
      - pkg-config
      - libmtdev-dev
      - flex
      - libkrb5-dev
      - libopengl-dev
      - libglu1-mesa-dev
      - libb2-dev
      - libxcb-util-dev
      - cmake-data
      - libpng-dev
      - clang
      - libfreetype-dev
      - libts-dev
      - libxcb-composite0-dev
      - libxcb-ewmh-dev
      - libasound2-dev
      - libxcb-shape0-dev
      - libxcb-res0-dev
      - libxcb1-dev
      - libxcb-cursor-dev
      - libxcb-dpms0-dev
      - libsctp-dev
      - libxcb-dri3-dev
      - libnss3-dev
      - libxcb-xinerama0-dev
      - python3-html5lib
      - libdbus-1-dev
      - libxcb-xf86dri0-dev
      - bison
      - libxcb-present-dev
      - libxcb-randr0-dev
      - libgbm-dev
      - libxcb-shm0-dev
      - libxcb-sync-dev
      - libinput-dev
      - nodejs
      - libgtk-3-dev
      - libxcb-sync0-dev
      - libcups2-dev
      - libxshmfence-dev
      - libgstreamer1.0-dev
      - libclang-dev
      - dh-exec
      - libproxy-dev
      - libsqlite3-dev
      - libglx-dev
      - libxcb-xkb-dev
      - libxcb-screensaver0-dev
      - libpcre2-dev
      - libharfbuzz-dev
      - libxcb-damage0-dev
      - default-libmysqlclient-dev
      - libxfixes-dev
      - libx11-xcb-dev
      - libvulkan-dev
      - libmd4c-dev
      - libxcb-render0-dev
      - libxcb-keysyms1-dev
      - libxcb-xfixes0-dev
      - ninja-build
      - libwayland-dev
      - libgles-dev
      - libxcb-xinput-dev
      - libxext-dev
      - libfreetype6-dev
      - libudev-dev
      - libmd4c-html0-dev
      - libxcb-icccm4-dev
      - libwayland-egl1-mesa
      - libhunspell-dev
      - libfontconfig1-dev
      - libxcb-image0-dev
      - libxi-dev
      - libssl-dev
      - libxtst-dev
      - nodejs
      - libxkbfile-dev
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/etc/$CRAFT_PART_NAME
      cp $CRAFT_PART_BUILD/config.summary $CRAFT_PART_INSTALL/etc/$CRAFT_PART_NAME
    stage-packages:
      - libpq5
      - libxcb-glx0
      - libjpeg8
      - libdrm-common
      - libxcb-render-util0
      - libxcursor1
      - zlib1g
      - liblttng-ust1
      - libxkbcommon-x11-0
      - libxcomposite1
      - libatspi2.0-0
      - libxcb-xtest0
      - firebird3.0-common
      - libxrender1
      - libxcb-record0
      - libgl1-mesa-glx
      - libglib2.0-0
      - libxcb-xvmc0
      - libxcb-xv0
      - libx11-6
      - libfontconfig
      - libxkbcommon0
      - libxcb-dri2-0
      - libicu70
      - libgl1
      - libdouble-conversion3
      - libgles2-mesa
      - llvm
      - libzstd1
      - unixodbc
      - libsystemd0
      - libxcb-xrm0
      - libmtdev1
      - libkrb5-3
      - libopengl0
      - libglu1-mesa
      - libb2-1
      - libxcb-util1
      - libpng16-16
      - libts0
      - libxcb-composite0
      - libxcb-ewmh2
      - libasound2
      - libxcb-shape0
      - libxcb-res0
      - libxcb1
      - libxcb-cursor0
      - libxcb-dpms0
      - libsctp1
      - libxcb-dri3-0
      - libnss3
      - libxcb-xinerama0
      - libdbus-1-3
      - libxcb-xf86dri0
      - libxcb-present0
      - libxcb-randr0
      - libgbm1
      - libxcb-shm0
      - libinput10
      - libgtk-3-0
      - libxcb-sync1
      - libcups2
      - libxshmfence1
      - libgstreamer1.0-0
      - libclang1
      - libproxy1v5
      - libsqlite3-0
      - libglx0
      - libxcb-xkb1
      - libxcb-screensaver0
      - libpcre2-32-0
      - libharfbuzz0b
      - libxcb-damage0
      - libmysqlclient21
      - libxfixes3
      - libx11-xcb1
      - libvulkan1
      - libmd4c0
      - libxcb-render0
      - libxcb-keysyms1
      - libxcb-xfixes0
      - libwayland-server0
      - libgles1
      - libxcb-xinput0
      - libxext6
      - libfreetype6
      - libudev1
      - libmd4c-html0
      - libxcb-icccm4
      - libhunspell-1.7-0
      - libfontconfig1
      - libxcb-image0
      - libxi6
      - libssl3
      - libxtst6
      - libxkbfile1
    override-stage: |
      craftctl default
      find $CRAFT_STAGE -type f,l -name "*.pc" -exec bash -c "sed -i 's:/root/stage:/snap/qt-framework-sdk/current:g' {}*" \;

